remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [Desbordante user guide]
description: [This manual explores the main Desbordante concepts and navigates
  through the general usage scenario.]
